fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/MarcoGorelli/madforhooks
    rev: 0.3.0
    hooks:
      - id: no-print-statements
