fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/MarcoGorelli/madforhooks
    rev: 0.4.1
    hooks:
      - id: no-print-statements
