name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    name: Set up Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge, defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Install preliz
        shell: bash -l {0}
        run: |
          conda install pip
          pip install -r requirements-dev.txt
          pip install ".[full]"
          python --version
          conda list
          pip freeze
      - name: Run linters
        shell: bash -l {0}
        run: |
          python -m black preliz --check
          echo "Success!"
          echo "Checking code style with pylint..."
          python -m pylint preliz/
      - name: Run tests
        shell: bash -l {0}
        run: |
          python -m pytest -vv --cov=preliz --cov-report=term --cov-report=xml preliz/tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
